format_version: v1.0
type: UniqueComponent
attributes: {id: rng}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: RNGCON_CONT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysOtaPic32mzw1, value: '1'}
  - type: KeyValueSet
    attributes: {id: RNGCON_PRNGEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysOtaPic32mzw1, value: '1'}
  - type: KeyValueSet
    attributes: {id: RNGCON_TRNGEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysOtaPic32mzw1, value: '1'}
  - type: Hex
    attributes: {id: RNGCON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rng, value: '1792'}
- type: ElementPosition
  attributes: {x: '250', y: '300', id: rng}
