format_version: v1.0
type: UniqueComponent
attributes: {id: sys_fs}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SYS_FS_MAX_FILES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysOtaPic32mzw1, value: '5'}
      - type: User
        attributes: {value: '5'}
  - type: Integer
    attributes: {id: SYS_FS_RTOS_DELAY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysOtaPic32mzw1, value: '1'}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: sys_fs_DRV_MEDIA_dependency}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: drv_memory_0, targetAttachmentID: drv_media}
- type: ElementPosition
  attributes: {x: '550', y: '460', id: sys_fs}
