format_version: v1.0
type: GroupComponent
attributes: {displayName: Systme Configuration, id: Systme Configuration}
children:
- type: ElementPosition
  attributes: {x: '384', y: '40', id: Systme Configuration}
