format_version: v1.0
type: UniqueComponent
attributes: {id: sysWssPic32mzw1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SYS_WSS_MAX_NUM_CLIENTS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Menu
    attributes: {id: WSS_RTOS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '127', y: '107', id: sysWssPic32mzw1}
