package:
  format-version: "1.0.0"
  name: "wireless_apps_pic32mzw1_wfi32e01"
  type: "application"
  status: "production"
  required: true
  version: "v3.8.0"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.17.0"
    - name: "core"
      type: "package"
      version: "v3.13.1"
    - name: "crypto"
      type: "package"
      version: "v3.8.0"
    - name: "cryptoauthlib"
      type: "package"
      version: "v3.3.3"
    - name: "csp"
      type: "package"
      version: "v3.18.0"
    - name: "dev_packs"
      type: "package"
      version: "v3.18.0"
    - name: "net"
      type: "package"
      version: "v3.10.0"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.9.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.4.6"
    - name: "paho.mqtt.embedded-c"
      type: "package"
      version: "v1.2.3"
    - name: "usb"
      type: "package"
      version: "v3.10.0"
    - name: "wireless_system_pic32mzw1_wfi32e01"
      type: "package"
      version: "v3.8.0"
    - name: "touch"
      type: "package"
      version: "v3.12.1"
      
      
      
