format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_WIFI_AP_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysOtaPic32mzw1, value: 'false'}
  - type: Boolean
    attributes: {id: SYS_WIFI_AP_SSIDVISIBILE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: SYS_WIFI_STA_SSID_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: riodemo139}
- type: ElementPosition
  attributes: {x: '460', y: '20', id: sysWifiPic32mzw1}
