configName: wfi32_iot
folderName: wfi32_iot
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32MZ1025W104132
projectName: paho_mqtt_client_power_save_wfi32_iot
settings:
  PackageFilter: bsp;core;core_apps_pic32mz_w1;crypto;cryptoauthlib;csp;csp_apps_pic32mz_w1;dev_packs;net;quick_docs;touch;usb;wireless_apps_pic32mzw1_wfi32e01;wireless_apps_pic32mzw1_wfi32e01_old;wireless_system_pic32mzw1_wfi32e01;wireless_system_pic32mzw1_wfi32e01_last;wireless_system_pic32mzw1_wfi32e01_old;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_RECENT
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.5.203\atdf\PIC32MZ1025W104132.atdf
