configName: pic32mz_w1_curiosity
folderName: pic32mz_w1_curiosity
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32MZ1025W104132
projectName: paho_mqtt_client_pic32mz_w1_curiosity
settings:
  PackageFilter: bsp;core;crypto;cryptoauthlib;csp;dev_packs;net;quick_docs;touch;usb;wireless_apps_pic32mzw1_wfi32e01;wireless_system_pic32mzw1_wfi32e01;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.5.203\atdf\PIC32MZ1025W104132.atdf
