format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: Menu
    attributes: {id: SYS_WIFI_RTOS_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: SYS_WIFI_SYS_RTOS_TASK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: sysWifiPic32mzw1}
