format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: SYS_WIFI_STA_PWD_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: password}
- type: ElementPosition
  attributes: {x: '480', y: '20', id: sysWifiPic32mzw1}
