format_version: v1.0
type: UniqueComponent
attributes: {id: net_Pres}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: NET_PRES_BLOB_CERT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: '1'}
  - type: Boolean
    attributes: {id: NET_PRES_BLOB_CERT_REPO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'false'}
  - type: Boolean
    attributes: {id: NET_PRES_CERT_STORE_STUBS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
  - type: KeyValueSet
    attributes: {id: NET_PRES_ENC_PROVIDE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_GENERATE_ENC_STUBS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_CLIENT_ENC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_DATAGRAM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_DATAGRAM_ENC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_ENCRYPTION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_SERVER_ENC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_STREAM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_STREAM_ENC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_USE_WOLF_SSL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'false'}
- type: ElementPosition
  attributes: {x: '20', y: '20', id: net_Pres}
