format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipDhcps}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_IP_ADDRESS_RANGE_START_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.100.10}
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_SERVER_GATEWAY_ADDRESS_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.100.1}
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_SERVER_IP_ADDRESS_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.100.1}
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_SERVER_NETMASK_ADDRESS_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_SERVER_PRIMARY_DNS_ADDRESS_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.100.1}
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_SERVER_SECONDARY_DNS_ADDRESS_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.100.1}
  - type: Integer
    attributes: {id: TCPIP_DHCP_SERVER_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDhcps, value: '492'}
  - type: Boolean
    attributes: {id: TCPIP_DHCP_SERVER_IDX1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDhcps, value: 'false'}
  - type: Integer
    attributes: {id: TCPIP_DHCP_SERVER_INSTANCES_NUMBER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: TCPIP_DHCP_SERVER_INTERFACE_INDEX_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_DHCP_SERVER_POOL_ENABLED_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '320', y: '20', id: tcpipDhcps}
