files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 58D7061AA26CEC55F9EE626816454E5C
  logicalPath: config\pic32mzw1
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 58D7061AA26CEC55F9EE626816454E5C
- generatedChecksum: 9A1AF5B6A15F9FB14FF072EEF3710046
  logicalPath: config\pic32mzw1
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9A1AF5B6A15F9FB14FF072EEF3710046
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5865B2DA3BF4DFAB66F166215B1EB9D6
  logicalPath: config\pic32mzw1\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5865B2DA3BF4DFAB66F166215B1EB9D6
- generatedChecksum: 4F97496FDC02C3FF8C7051F3F76DC204
  logicalPath: config\pic32mzw1\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4F97496FDC02C3FF8C7051F3F76DC204
- generatedChecksum: 09374C3A1AE94C630AB9ACE6D0832D0F
  logicalPath: config\pic32mzw1\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 09374C3A1AE94C630AB9ACE6D0832D0F
- generatedChecksum: 302870B553042ED5294917554809F0B6
  logicalPath: config\pic32mzw1\peripheral\nvm
  name: plib_nvm.c
  physicalPath: peripheral\nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 302870B553042ED5294917554809F0B6
- generatedChecksum: 1894C54565C113FA18850D883EFBB3D8
  logicalPath: config\pic32mzw1\peripheral\spi\spi_master
  name: plib_spi1_master.c
  physicalPath: peripheral\spi\spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1894C54565C113FA18850D883EFBB3D8
- generatedChecksum: 6EA296E761CC386337D25573B177B335
  logicalPath: config\pic32mzw1\peripheral\uart
  name: plib_uart1.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6EA296E761CC386337D25573B177B335
- generatedChecksum: 640A4B35B8CDB53BD8EA5077D81386BE
  logicalPath: config\pic32mzw1\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 640A4B35B8CDB53BD8EA5077D81386BE
- generatedChecksum: FED2C78FCFDFAEC2E4AC890703B77760
  logicalPath: config\pic32mzw1
  name: system_pmu_mldo_trim.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: FED2C78FCFDFAEC2E4AC890703B77760
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config\pic32mzw1
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 684C1B450BD0C0ADF455296291954A10
  logicalPath: config\pic32mzw1\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 684C1B450BD0C0ADF455296291954A10
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 76016C9804D6DE17B74C92D82294562E
  logicalPath: config\pic32mzw1
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 76016C9804D6DE17B74C92D82294562E
- generatedChecksum: F5F076467F5EE568C8208D1E3C98E8EB
  logicalPath: config\pic32mzw1
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F5F076467F5EE568C8208D1E3C98E8EB
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config\pic32mzw1
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\pic32mzw1\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config\pic32mzw1\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B358678B02AC7D3AD6CC80621ECC826D
  logicalPath: config\pic32mzw1\osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B358678B02AC7D3AD6CC80621ECC826D
- generatedChecksum: 9238A3759A2C6748FE493370DE35B5E0
  logicalPath: config\pic32mzw1\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 9238A3759A2C6748FE493370DE35B5E0
- generatedChecksum: 7F65C8062DF1367D5D6B401389DA270A
  logicalPath: config\pic32mzw1\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 7F65C8062DF1367D5D6B401389DA270A
- generatedChecksum: F342288057B1DA1774434CE705A8E3EA
  logicalPath: config\pic32mzw1\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: F342288057B1DA1774434CE705A8E3EA
- generatedChecksum: FBB2DEFAADE0488ACAFA5C5FB807B149
  logicalPath: config\pic32mzw1\peripheral\nvm
  name: plib_nvm.h
  physicalPath: peripheral\nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: FBB2DEFAADE0488ACAFA5C5FB807B149
- generatedChecksum: 8B538ED26B7B1F9177E6F490AAE66B57
  logicalPath: config\pic32mzw1\peripheral\spi\spi_master
  name: plib_spi1_master.h
  physicalPath: peripheral\spi\spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 8B538ED26B7B1F9177E6F490AAE66B57
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config\pic32mzw1\peripheral\spi\spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral\spi\spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 2B111FC8ADC9E50611E481BE82CD3982
  logicalPath: config\pic32mzw1\peripheral\uart
  name: plib_uart1.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B111FC8ADC9E50611E481BE82CD3982
- generatedChecksum: CB4B34D1ABCE74BF62A89A7FF936BE91
  logicalPath: config\pic32mzw1\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: CB4B34D1ABCE74BF62A89A7FF936BE91
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config\pic32mzw1\system\debug
  name: sys_debug.h
  physicalPath: system\debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\pic32mzw1\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\pic32mzw1\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config\pic32mzw1\system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config\pic32mzw1\system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config\pic32mzw1\system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mzw1
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config\pic32mzw1
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mzw1;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mzw1;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
