format_version: v1.0
type: UniqueComponent
attributes: {id: sysNetPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_NET_ENABLE_SNI}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_NET_ENABLE_TLS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: SYS_NET_HOST_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: maker.ifttt.com}
  - type: Integer
    attributes: {id: SYS_NET_PORT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '443'}
  - type: Boolean
    attributes: {id: SYS_NET_RECONNECT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '65', y: '90', id: sysNetPic32mzw1}
