configName: pic32mz_w1_curiosity_freertos
folderName: pic32mz_w1_curiosity_freertos
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32MZ1025W104132
projectName: paho_mqtt_tls_client_pic32mz_w1_curiosity_freertos
settings:
  PackageFilter: bootloader;bootloader_apps_uart;bsp;core;crypto;cryptoauthlib;csp;net;quick_docs;usb;wireless_apps_pic32mzw1_wfi32e01;wireless_apps_winc1500;wireless_apps_winc3400;wireless_system_pic32mzw1_wfi32e01;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.4.193\atdf\PIC32MZ1025W104132.atdf
