format_version: v1.0
type: UniqueComponent
attributes: {id: sysNetPic32mzw1}
children:
- type: Symbols
  children:
  - type: Menu
    attributes: {id: SYS_NET_APPDEBUG_FLOW_CONFIG_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: SYS_NET_APPDEBUG_PRESTR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: SYS_NET_ENABLE_TLS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysMqttPic32mzw1, value: 'true'}
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '20', y: '19', id: sysNetPic32mzw1}
