format_version: v1.0
type: UniqueComponent
attributes: {id: sysNetPic32mzw1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: SYS_NET_HOST_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: api.openweathermap.org}
  - type: Integer
    attributes: {id: SYS_NET_PORT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '80'}
  - type: Boolean
    attributes: {id: SYS_NET_RECONNECT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '171', y: '173', id: sysNetPic32mzw1}
