format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiProvPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_WIFIPROV_APPDEBUG_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiProvPic32mzw1, value: 'false'}
  - type: Boolean
    attributes: {id: SYS_WIFIPROV_AP_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiProvPic32mzw1, value: 'false'}
- type: ElementPosition
  attributes: {x: '176', y: '308', id: sysWifiProvPic32mzw1}
